/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["api_views_hello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anzctr-trials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Anzctr Trials */
        get: operations["api_views_list_anzctr_trials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/anzctr-trials/{reg_no}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Anzctr Trial */
        get: operations["api_views_get_anzctr_trial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/test-worker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Test Worker */
        get: operations["api_views_test_worker"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clin-trials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Clin Trials */
        get: operations["api_views_list_clin_trials"];
        put?: never;
        /** Create Clin Trial */
        post: operations["api_views_create_clin_trial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clin-trials/{nct_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Clin Trial */
        get: operations["api_views_get_clin_trial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Gen Trials */
        get: operations["api_views_list_gen_trials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trials/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Gen Trial */
        get: operations["api_views_get_gen_trial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Input */
        Input: {
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** AnzctrTrialBrief */
        AnzctrTrialBrief: {
            /** Registration Number */
            registration_number: string;
            /** Public Title */
            public_title?: string | null;
            /** Recruitment Status */
            recruitment_status?: string | null;
            /** Description */
            description?: string | null;
            /** Date Last Updated */
            date_last_updated?: string | null;
        };
        /** PagedAnzctrTrialBrief */
        PagedAnzctrTrialBrief: {
            /** Items */
            items: components["schemas"]["AnzctrTrialBrief"][];
            /** Count */
            count: number;
        };
        /** AnzctrTrialFull */
        AnzctrTrialFull: {
            /** ID */
            id?: number | null;
            /** Registration Number */
            registration_number: string;
            /** Ethics Status */
            ethics_status?: string | null;
            /** Date Submitted */
            date_submitted?: string | null;
            /** Date Registered */
            date_registered?: string | null;
            /** Date Last Updated */
            date_last_updated?: string | null;
            /** Public Title */
            public_title?: string | null;
            /** Scientific Title */
            scientific_title?: string | null;
            /** Secondary Id */
            secondary_id?: unknown[] | null;
            /** Universal Trial Number */
            universal_trial_number?: string | null;
            /** Health Condition */
            health_condition?: unknown[] | null;
            /** Condition Category */
            condition_category?: unknown[] | null;
            /** Condition Code */
            condition_code?: unknown[] | null;
            /** Study Type */
            study_type?: string | null;
            /** Description */
            description?: string | null;
            /** Intervention Code */
            intervention_code?: unknown[] | null;
            /** Comparator */
            comparator?: string | null;
            /** Control Group */
            control_group?: string | null;
            /** Primary Outcome */
            primary_outcome?: unknown[] | null;
            /** Primary Assessment Method */
            primary_assessment_method?: unknown[] | null;
            /** Primary Timepoint */
            primary_timepoint?: unknown[] | null;
            /** Secondary Outcome */
            secondary_outcome?: unknown[] | null;
            /** Secondary Assessment Method */
            secondary_assessment_method?: unknown[] | null;
            /** Secondary Timepoint */
            secondary_timepoint?: unknown[] | null;
            /** Inclusion Criteria */
            inclusion_criteria?: string | null;
            /** Min Age */
            min_age?: string | null;
            /** Max Age */
            max_age?: string | null;
            /** Sex */
            sex?: string | null;
            /** Healthy Volunteers */
            healthy_volunteers?: string | null;
            /** Exclusion Criteria */
            exclusion_criteria?: string | null;
            /** Purpose */
            purpose?: string | null;
            /** Intervention Allocation */
            intervention_allocation?: string | null;
            /** Enrolling Procedure */
            enrolling_procedure?: string | null;
            /** Sequence Generation */
            sequence_generation?: string | null;
            /** Masking Blinding */
            masking_blinding?: string | null;
            /** Who Mask Blind */
            who_mask_blind?: string | null;
            /** Intervention Assignment */
            intervention_assignment?: string | null;
            /** Other Design Features */
            other_design_features?: string | null;
            /** Phase */
            phase?: string | null;
            /** Endpoint Type */
            endpoint_type?: string | null;
            /** Statistical Methods */
            statistical_methods?: string | null;
            /** Recruitment Status */
            recruitment_status?: string | null;
            /** Summary */
            summary?: string | null;
            /** Trial Page Url */
            trial_page_url?: string | null;
        };
        /** ClinTrialBrief */
        ClinTrialBrief: {
            /** Nct Id */
            nct_id: string;
            /** Official Title */
            official_title: string;
            /** Overall Status */
            overall_status?: string | null;
            /** Brief Summary */
            brief_summary?: string | null;
            /** Last Update Post Date */
            last_update_post_date: string;
        };
        /** PagedClinTrialBrief */
        PagedClinTrialBrief: {
            /** Items */
            items: components["schemas"]["ClinTrialBrief"][];
            /** Count */
            count: number;
        };
        /** ClinTrialFull */
        ClinTrialFull: {
            /** ID */
            id?: number | null;
            /** Nct Id */
            nct_id: string;
            /** Last Update Post Date */
            last_update_post_date: string;
            /** Brief Title */
            brief_title?: string | null;
            /** Official Title */
            official_title: string;
            /** Organization */
            organization?: string | null;
            /** Overall Status */
            overall_status?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** Completion Date */
            completion_date?: string | null;
            /** Lead Sponsor */
            lead_sponsor?: string | null;
            /** Collaborators */
            collaborators?: unknown[] | null;
            /** Brief Summary */
            brief_summary?: string | null;
            /** Detailed Description */
            detailed_description?: string | null;
            /** Study Type */
            study_type?: string | null;
            /** Conditions */
            conditions?: unknown[] | null;
            /** Condition Keywords */
            condition_keywords?: unknown[] | null;
            /** Phases */
            phases?: unknown[] | null;
            /** Target Duration */
            target_duration?: string | null;
            /** Allocation */
            allocation?: string | null;
            /** Intervention Model */
            intervention_model?: string | null;
            /** Intervention Model Description */
            intervention_model_description?: string | null;
            /** Primary Purpose */
            primary_purpose?: string | null;
            /** Observational Model */
            observational_model?: string | null;
            /** Time Perspective */
            time_perspective?: string | null;
            /** Masking */
            masking?: string | null;
            /** Masking Description */
            masking_description?: string | null;
            /** Who Masked */
            who_masked?: unknown[] | null;
            /** Biospec Description */
            biospec_description?: string | null;
            /** Biospec Retention */
            biospec_retention?: string | null;
            /** Enrollment Count */
            enrollment_count?: number | null;
            /** Enrollment Type */
            enrollment_type?: string | null;
            /** Intervention Type */
            intervention_type?: unknown[] | null;
            /** Intervention Name */
            intervention_name?: unknown[] | null;
            /** Intervention Description */
            intervention_description?: unknown[] | null;
            /** Primary Outcome Measure */
            primary_outcome_measure?: unknown[] | null;
            /** Primary Outcome Description */
            primary_outcome_description?: unknown[] | null;
            /** Primary Outcome Timeframe */
            primary_outcome_timeframe?: unknown[] | null;
            /** Secondary Outcome Measure */
            secondary_outcome_measure?: unknown[] | null;
            /** Secondary Outcome Description */
            secondary_outcome_description?: unknown[] | null;
            /** Secondary Outcome Timeframe */
            secondary_outcome_timeframe?: unknown[] | null;
            /** Other Outcome Measure */
            other_outcome_measure?: unknown[] | null;
            /** Other Outcome Description */
            other_outcome_description?: unknown[] | null;
            /** Other Outcome Timeframe */
            other_outcome_timeframe?: unknown[] | null;
            /** Eligibility Criteria */
            eligibility_criteria?: string | null;
            /** Eligibility Healthy Volunteers */
            eligibility_healthy_volunteers?: boolean | null;
            /** Eligibility Gender Based */
            eligibility_gender_based?: boolean | null;
            /** Eligibility Sex */
            eligibility_sex?: string | null;
            /** Eligibility Gender Description */
            eligibility_gender_description?: string | null;
            /** Eligibility Minage */
            eligibility_minage?: string | null;
            /** Eligibility Maxage */
            eligibility_maxage?: string | null;
            /** Eligibility Stdages */
            eligibility_stdages?: unknown[] | null;
            /** Eligibility Study Population */
            eligibility_study_population?: string | null;
            /** Eligibility Sampling Method */
            eligibility_sampling_method?: string | null;
            /** Central Contact Name */
            central_contact_name?: unknown[] | null;
            /** Central Contact Email */
            central_contact_email?: unknown[] | null;
        };
        /** GenTrialBrief */
        GenTrialBrief: {
            /** Tid */
            tid: string;
            /** Brief Title */
            brief_title?: string | null;
            /** Status */
            status?: string | null;
            /** Summary */
            summary?: string | null;
            /** Last Update Date */
            last_update_date: string;
        };
        /** PagedGenTrialBrief */
        PagedGenTrialBrief: {
            /** Items */
            items: components["schemas"]["GenTrialBrief"][];
            /** Count */
            count: number;
        };
        /** GenTrialFull */
        GenTrialFull: {
            /** ID */
            id?: number | null;
            /** Tid */
            tid: string;
            /** Last Update Date */
            last_update_date: string;
            /** Source Table */
            source_table: string;
            /** Brief Title */
            brief_title?: string | null;
            /** Scientific Title */
            scientific_title?: string | null;
            /** Status */
            status?: string | null;
            /** Summary */
            summary?: string | null;
            /** Description */
            description?: string | null;
            /** Study Type */
            study_type?: string | null;
            /** Conditions */
            conditions?: unknown[] | null;
            /** Purpose */
            purpose?: string | null;
            /** Enrollment Procedure */
            enrollment_procedure?: string | null;
            /** Intervention Code */
            intervention_code?: unknown[] | null;
            /** Intervention Description */
            intervention_description?: string | null;
            /** Primary Outcome Measure */
            primary_outcome_measure?: unknown[] | null;
            /** Primary Outcome Description */
            primary_outcome_description?: unknown[] | null;
            /** Primary Outcome Timeframe */
            primary_outcome_timeframe?: unknown[] | null;
            /** Secondary Outcome Measure */
            secondary_outcome_measure?: unknown[] | null;
            /** Secondary Outcome Description */
            secondary_outcome_description?: unknown[] | null;
            /** Secondary Outcome Timeframe */
            secondary_outcome_timeframe?: unknown[] | null;
            /** Eligibility Criteria */
            eligibility_criteria?: string | null;
            /** Healthy Volunteers */
            healthy_volunteers?: string | null;
            /** Sex */
            sex?: string | null;
            /** Minage */
            minage?: string | null;
            /** Maxage */
            maxage?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_views_hello: {
        parameters: {
            query?: {
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_views_list_anzctr_trials: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedAnzctrTrialBrief"];
                };
            };
        };
    };
    api_views_get_anzctr_trial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reg_no: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnzctrTrialFull"];
                };
            };
        };
    };
    api_views_test_worker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    api_views_list_clin_trials: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedClinTrialBrief"];
                };
            };
        };
    };
    api_views_create_clin_trial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClinTrialFull"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinTrialFull"];
                };
            };
        };
    };
    api_views_get_clin_trial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                nct_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClinTrialFull"];
                };
            };
        };
    };
    api_views_list_gen_trials: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedGenTrialBrief"];
                };
            };
        };
    };
    api_views_get_gen_trial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenTrialFull"];
                };
            };
        };
    };
}
